### ISSUE TITLE
Simulation setup steps checklist

### ISSUE THREAD

**Issue by TomNicholas** [CWorthy-ocean/roms-tools#1]
We want to translate all the MATLAB setup tools into Python, including:

- [x] Step 1: Make grid
- [ ] Step 2: Make topography
- [ ] Step 3: Make tides
- [ ] Step 4: Make atmospheric forcing
- [ ] Step 5: Make initial conditions
- [ ] Step 6: Make boundary forcing
- [ ] Step 7: Set up nesting (optional for user)
